name: districtdesigngroup
favicon: null
layout_spectrum: 0.25025
typography_spectrum: 0.299310106318444
title: districtdesigngroup
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2f4367'
    - '#ffff00'
    - '#000000'
    - '#0000ff'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.25
  rhythmicContrast: 0.9140514065511525
purpose: []
